# -*- coding: utf-8 -*-
AWS_REGION = "eu-west-2"
SLACK_TOKEN = "MY_TOKEN"
SLACK_CHANNEL = "MY_CHANNEL"
KEEP_MIN_IMAGE_COUNT = 3
KEEP_IMAGES_NEWER_THAN_DAYS = 7
SLACK_MAX_MESSAGE_LENGTH = 4000
DELETE_ENABLED = False
